name: Prototype check SEN issue

# Run this workflow every time a new issue is made on the repository
on:
  issues:
   types: [opened]

jobs:
  issue-checker:
    name: Check Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test Issue-checker
        uses: sfu-dhil/issue-templates@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          templates: '["bug_report.md"]'

